# Generated by Django 5.0.1 on 2025-11-20 20:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_transaction', models.BooleanField(default=True, help_text='Receive email for transaction alerts')),
                ('email_goal', models.BooleanField(default=True, help_text='Receive email for goal milestones')),
                ('email_budget', models.BooleanField(default=True, help_text='Receive email for budget alerts')),
                ('email_account', models.BooleanField(default=True, help_text='Receive email for account issues')),
                ('email_system', models.BooleanField(default=True, help_text='Receive email for system announcements')),
                ('push_transaction', models.BooleanField(default=True, help_text='Receive in-app notification for transaction alerts')),
                ('push_goal', models.BooleanField(default=True, help_text='Receive in-app notification for goal milestones')),
                ('push_budget', models.BooleanField(default=True, help_text='Receive in-app notification for budget alerts')),
                ('push_account', models.BooleanField(default=True, help_text='Receive in-app notification for account issues')),
                ('push_system', models.BooleanField(default=True, help_text='Receive in-app notification for system announcements')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
