# Generated by Django 5.0.1 on 2025-12-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0002_notificationpreference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('transaction', 'Transaction'), ('goal', 'Goal'), ('budget', 'Budget'), ('account', 'Account'), ('system', 'System')], default='system', max_length=20),
        ),
    ]
