# Generated by Django 5.0.1 on 2025-12-06 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.CharField(choices=[('transaction', 'Transaction'), ('goal', 'Goal'), ('budget', 'Budget'), ('account', 'Account'), ('bill', 'Bill'), ('system', 'System')], default='system', max_length=20),
        ),
    ]
