# Generated by Django 5.0.1 on 2025-12-04 18:46

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Insight',
            fields=[
                ('insight_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('insight_type', models.CharField(choices=[('subscription', 'Subscription Pattern'), ('unusual_spending', 'Unusual Spending'), ('merchant_pattern', 'Merchant Pattern'), ('savings_opportunity', 'Savings Opportunity'), ('income_analysis', 'Income Analysis'), ('spending_trend', 'Spending Trend'), ('budget_insight', 'Budget Insight')], help_text='Type of insight', max_length=50)),
                ('title', models.CharField(help_text='Short title for the insight', max_length=200)),
                ('description', models.TextField(help_text='Detailed description of the insight')),
                ('priority', models.CharField(choices=[('high', 'High'), ('medium', 'Medium'), ('low', 'Low')], default='medium', help_text='Priority level of the insight', max_length=20)),
                ('is_dismissed', models.BooleanField(default=False, help_text='Whether the user has dismissed this insight')),
                ('is_read', models.BooleanField(default=False, help_text='Whether the user has read this insight')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Additional data like related IDs, amounts, percentages')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('expires_at', models.DateTimeField(blank=True, help_text='When this insight expires and should be hidden', null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Insight',
                'verbose_name_plural': 'Insights',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InsightFeedback',
            fields=[
                ('feedback_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('is_helpful', models.BooleanField(help_text='Whether the user found this insight helpful')),
                ('feedback_text', models.TextField(blank=True, help_text='Optional text feedback from user')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('insight', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='insights.insight')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insight_feedback', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Insight Feedback',
                'verbose_name_plural': 'Insight Feedback',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='insight',
            index=models.Index(fields=['user', 'is_dismissed'], name='insights_in_user_id_27574b_idx'),
        ),
        migrations.AddIndex(
            model_name='insight',
            index=models.Index(fields=['user', 'insight_type'], name='insights_in_user_id_4932ce_idx'),
        ),
        migrations.AddIndex(
            model_name='insight',
            index=models.Index(fields=['created_at'], name='insights_in_created_c34a89_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='insightfeedback',
            unique_together={('insight', 'user')},
        ),
    ]
