# Generated by Django 5.0.1 on 2025-12-18 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insight',
            name='insight_type',
            field=models.CharField(choices=[('subscription', 'Subscription Pattern'), ('unusual_spending', 'Unusual Spending'), ('merchant_pattern', 'Merchant Pattern'), ('savings_opportunity', 'Savings Opportunity'), ('income_analysis', 'Income Analysis'), ('spending_trend', 'Spending Trend'), ('budget_insight', 'Budget Insight'), ('ai_recommendation', 'AI Recommendation')], help_text='Type of insight', max_length=50),
        ),
    ]
