# Generated by Django 5.0.1 on 2025-11-11 06:23

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('category_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(100)])),
                ('type', models.CharField(choices=[('income', 'Income'), ('expense', 'Expense'), ('transfer', 'Transfer')], max_length=20)),
                ('icon', models.CharField(blank=True, help_text='Icon identifier', max_length=50)),
                ('color', models.CharField(default='#000000', help_text='Hex color code', max_length=7)),
                ('is_system_category', models.BooleanField(default=False)),
                ('rules', models.JSONField(blank=True, default=dict, help_text='Auto-categorization rules')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent_category', models.ForeignKey(blank=True, help_text='For subcategories', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subcategories', to='transactions.category')),
                ('user', models.ForeignKey(blank=True, help_text='Null for system categories', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Positive for income, negative for expenses', max_digits=10)),
                ('date', models.DateField()),
                ('merchant_name', models.CharField(max_length=200, validators=[django.core.validators.MinLengthValidator(2), django.core.validators.MaxLengthValidator(200)])),
                ('description', models.TextField(blank=True)),
                ('subcategory', models.CharField(blank=True, max_length=100, null=True)),
                ('tags', models.JSONField(blank=True, default=list, help_text='Array of tag strings')),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_recurring', models.BooleanField(default=False)),
                ('is_transfer', models.BooleanField(default=False, help_text='Internal transfer between accounts')),
                ('plaid_transaction_id', models.CharField(blank=True, db_index=True, help_text='External transaction identifier from Plaid', max_length=255, null=True, unique=True)),
                ('location', models.JSONField(blank=True, default=dict, help_text='Location data: latitude, longitude, address')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_modified', models.BooleanField(default=False, help_text='Whether user manually edited this transaction')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='accounts.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='transactions.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Transaction',
                'verbose_name_plural': 'Transactions',
                'db_table': 'transactions',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['user', 'type'], name='categories_user_id_418e53_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['is_system_category'], name='categories_is_syst_780d98_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('user', 'name', 'type')},
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['user', 'date'], name='transaction_user_id_059bf9_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['account', 'date'], name='transaction_account_f34883_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['category', 'date'], name='transaction_categor_3ca96c_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['plaid_transaction_id'], name='transaction_plaid_t_3baf81_idx'),
        ),
    ]
