# Generated by Django 5.0.1 on 2025-12-08 04:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0003_receipt_transactionsplit'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='is_recurring_dismissed',
            field=models.BooleanField(default=False, help_text='User explicitly dismissed recurring status'),
        ),
    ]
