# Generated by Django 5.0.1 on 2025-12-09 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0004_transaction_is_recurring_dismissed'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='rules_combination',
            field=models.CharField(choices=[('AND', 'All rules must match'), ('OR', 'Any rule can match')], default='AND', help_text='How to combine multiple rules when categorizing transactions', max_length=3),
        ),
    ]
