# Generated by Django 5.0.1 on 2025-12-14 09:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0002_fix_empty_rules'),
        ('transactions', '0005_add_rules_combination'),
    ]

    operations = [
    ]
