# Generated by Django 5.0.1 on 2025-12-16 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transactions', '0006_merge_0002_fix_empty_rules_0005_add_rules_combination'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='rules',
            field=models.JSONField(blank=True, default=list, help_text='Auto-categorization rules'),
        ),
    ]
