# Generated by Django 5.0.1 on 2025-11-12 19:16

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0001_initial'),
        ('transactions', '0002_add_plaid_category_field'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contribution',
            fields=[
                ('contribution_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('source', models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic from Transaction')], default='manual', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contribution',
                'verbose_name_plural': 'Contributions',
                'db_table': 'contributions',
                'ordering': ['-date', '-created_at'],
            },
        ),
        migrations.AddField(
            model_name='goal',
            name='archived_at',
            field=models.DateTimeField(blank=True, help_text='When goal was archived', null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='completed_at',
            field=models.DateTimeField(blank=True, help_text='When goal was completed', null=True),
        ),
        migrations.AddField(
            model_name='goal',
            name='inferred_category',
            field=models.ForeignKey(blank=True, help_text='Category to track for automatic contributions', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goals', to='transactions.category'),
        ),
        migrations.AddField(
            model_name='goal',
            name='is_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='goal',
            name='priority',
            field=models.IntegerField(default=0, help_text='Goal priority for allocation'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'is_completed'], name='goals_user_id_d66208_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['inferred_category'], name='goals_inferre_686580_idx'),
        ),
        migrations.AddIndex(
            model_name='goal',
            index=models.Index(fields=['user', 'archived_at'], name='goals_user_id_596bf9_idx'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='goal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='goals.goal'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='transaction',
            field=models.ForeignKey(blank=True, help_text='Transaction that triggered this contribution (if automatic)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='goal_contributions', to='transactions.transaction'),
        ),
        migrations.AddField(
            model_name='contribution',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goal_contributions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['goal', 'date'], name='contributio_goal_id_0ee798_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['user', 'date'], name='contributio_user_id_95f33d_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['source'], name='contributio_source_63d9c9_idx'),
        ),
        migrations.AddIndex(
            model_name='contribution',
            index=models.Index(fields=['transaction'], name='contributio_transac_0548b1_idx'),
        ),
    ]
