# Generated by Django 5.0.1 on 2025-11-14 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0003_add_account_linking_and_contribution_rules'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='goal',
            new_name='goals_destina_174bb0_idx',
            old_name='goals_destination_account_idx',
        ),
        migrations.RenameIndex(
            model_name='goal',
            new_name='goals_transfe_b8c9a2_idx',
            old_name='goals_transfer_authorized_idx',
        ),
        migrations.RenameIndex(
            model_name='transferauthorization',
            new_name='transfer_au_goal_id_d7f59f_idx',
            old_name='transfer_auth_goal_status_idx',
        ),
        migrations.RenameIndex(
            model_name='transferauthorization',
            new_name='transfer_au_plaid_a_196886_idx',
            old_name='transfer_auth_plaid_id_idx',
        ),
        migrations.RenameIndex(
            model_name='transferauthorization',
            new_name='transfer_au_expires_9b9a4f_idx',
            old_name='transfer_auth_expires_at_idx',
        ),
        migrations.AddField(
            model_name='transferauthorization',
            name='authorized_account_id',
            field=models.CharField(blank=True, help_text='Plaid account ID that was authorized (must match transfer account)', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='transferauthorization',
            name='authorized_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Amount authorized for this authorization (must match transfer amount)', max_digits=12, null=True),
        ),
    ]
