# Generated by Django 5.0.1 on 2025-11-22 09:49

import django.core.validators
import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goals', '0004_add_authorization_fields'),
        ('transactions', '0003_receipt_transactionsplit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavingsRule',
            fields=[
                ('rule_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('rule_type', models.CharField(choices=[('roundup', 'Round-up'), ('percentage', 'Percentage-based')], max_length=20)),
                ('trigger', models.CharField(choices=[('all_expenses', 'All Expenses'), ('income', 'Income Only'), ('category', 'Specific Category')], default='all_expenses', max_length=20)),
                ('percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='savings_rules', to='transactions.category')),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_rules', to='goals.goal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_rules', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'savings_rules',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SavingsContribution',
            fields=[
                ('contribution_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='automated_contributions', to='goals.goal')),
                ('transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='savings_contributions', to='transactions.transaction')),
                ('rule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contributions', to='goals.savingsrule')),
            ],
            options={
                'db_table': 'savings_contributions',
                'ordering': ['-applied_at'],
                'unique_together': {('rule', 'transaction')},
            },
        ),
    ]
