# Generated by Django 5.0.1 on 2025-12-06 07:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0008_add_mfa_backup_codes'),
        ('transactions', '0003_receipt_transactionsplit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Bill name (e.g., Netflix, Electric Bill)', max_length=200)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('frequency', models.CharField(choices=[('weekly', 'Weekly'), ('biweekly', 'Biweekly'), ('monthly', 'Monthly'), ('quarterly', 'Quarterly'), ('yearly', 'Yearly')], default='monthly', max_length=20)),
                ('due_day', models.IntegerField(help_text='Day of month/period when bill is due', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('next_due_date', models.DateField(help_text='Next payment due date')),
                ('last_paid_date', models.DateField(blank=True, help_text='Last payment date', null=True)),
                ('is_autopay', models.BooleanField(default=False, help_text='Whether bill is on autopay')),
                ('payee', models.CharField(blank=True, help_text='Payee/company name', max_length=200)),
                ('notes', models.TextField(blank=True)),
                ('reminder_days', models.IntegerField(default=3, help_text='Days before due date to send reminder', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(30)])),
                ('reminder_enabled', models.BooleanField(default=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, help_text='Linked payment account', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='accounts.account')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='transactions.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
                'db_table': 'bills',
                'ordering': ['next_due_date', 'name'],
            },
        ),
        migrations.CreateModel(
            name='BillPayment',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Actual amount paid', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='bills.bill')),
                ('transaction', models.ForeignKey(blank=True, help_text='Linked transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bill_payments', to='transactions.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bill_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bill Payment',
                'verbose_name_plural': 'Bill Payments',
                'db_table': 'bill_payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['user', 'is_active'], name='bills_user_id_b02f8b_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['user', 'next_due_date'], name='bills_user_id_2f9216_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['next_due_date', 'is_active'], name='bills_next_du_3e387e_idx'),
        ),
        migrations.AddIndex(
            model_name='bill',
            index=models.Index(fields=['frequency'], name='bills_frequen_5e33d2_idx'),
        ),
        migrations.AddIndex(
            model_name='billpayment',
            index=models.Index(fields=['bill', '-payment_date'], name='bill_paymen_bill_id_14173d_idx'),
        ),
        migrations.AddIndex(
            model_name='billpayment',
            index=models.Index(fields=['user', '-payment_date'], name='bill_paymen_user_id_36b188_idx'),
        ),
        migrations.AddIndex(
            model_name='billpayment',
            index=models.Index(fields=['transaction'], name='bill_paymen_transac_48200b_idx'),
        ),
    ]
