# Generated by Django 5.0.1 on 2025-11-14 20:36

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StripeWebhookEvent',
            fields=[
                ('event_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_event_id', models.CharField(db_index=True, help_text='Stripe event ID', max_length=255, unique=True)),
                ('event_type', models.CharField(db_index=True, help_text='Type of webhook event', max_length=100)),
                ('payload', models.JSONField(blank=True, default=dict, help_text='Full webhook payload')),
                ('processed', models.BooleanField(default=False, help_text='Whether event has been processed')),
                ('processed_at', models.DateTimeField(blank=True, help_text='When event was processed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Stripe Webhook Event',
                'verbose_name_plural': 'Stripe Webhook Events',
                'db_table': 'stripe_webhook_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['stripe_event_id'], name='stripe_webh_stripe__e9e10a_idx'), models.Index(fields=['event_type', 'processed'], name='stripe_webh_event_t_d2da5d_idx'), models.Index(fields=['processed', 'created_at'], name='stripe_webh_process_73f163_idx')],
            },
        ),
        migrations.CreateModel(
            name='PendingSubscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('payment_method_id', models.CharField(help_text='Stripe Payment Method ID', max_length=255)),
                ('plan', models.CharField(choices=[('premium', 'Premium'), ('pro', 'Pro')], help_text='Subscription plan', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], help_text='Billing cycle', max_length=20)),
                ('trial_enabled', models.BooleanField(default=True, help_text='Whether 7-day trial is enabled')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('failed', 'Failed'), ('completed', 'Completed')], default='pending', help_text='Processing status', max_length=20)),
                ('retry_count', models.IntegerField(default=0, help_text='Number of retry attempts')),
                ('error_message', models.TextField(blank=True, help_text='Error message if processing failed', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pending Subscription',
                'verbose_name_plural': 'Pending Subscriptions',
                'db_table': 'pending_subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='pending_sub_user_id_71879d_idx'), models.Index(fields=['status', 'created_at'], name='pending_sub_status_abee96_idx')],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('subscription_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('stripe_subscription_id', models.CharField(db_index=True, help_text='Stripe subscription ID', max_length=255, unique=True)),
                ('stripe_customer_id', models.CharField(db_index=True, help_text='Stripe customer ID', max_length=255)),
                ('status', models.CharField(choices=[('active', 'Active'), ('trialing', 'Trialing'), ('past_due', 'Past Due'), ('canceled', 'Canceled'), ('incomplete', 'Incomplete'), ('incomplete_expired', 'Incomplete Expired'), ('unpaid', 'Unpaid')], default='trialing', help_text='Current subscription status', max_length=20)),
                ('plan', models.CharField(choices=[('premium', 'Premium'), ('pro', 'Pro')], help_text='Subscription plan (premium or pro)', max_length=20)),
                ('billing_cycle', models.CharField(choices=[('monthly', 'Monthly'), ('annual', 'Annual')], help_text='Billing cycle (monthly or annual)', max_length=20)),
                ('price_id_monthly', models.CharField(help_text='Stripe Price ID for monthly billing', max_length=255)),
                ('price_id_annual', models.CharField(help_text='Stripe Price ID for annual billing', max_length=255)),
                ('current_period_start', models.DateTimeField(help_text='Start of current billing period')),
                ('current_period_end', models.DateTimeField(help_text='End of current billing period')),
                ('trial_start', models.DateTimeField(blank=True, help_text='Start of trial period', null=True)),
                ('trial_end', models.DateTimeField(blank=True, help_text='End of trial period', null=True)),
                ('cancel_at_period_end', models.BooleanField(default=False, help_text='Whether subscription will cancel at period end')),
                ('canceled_at', models.DateTimeField(blank=True, help_text='Date when subscription was canceled', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Subscription',
                'verbose_name_plural': 'Subscriptions',
                'db_table': 'subscriptions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', 'status'], name='subscriptio_user_id_8d58fd_idx'), models.Index(fields=['stripe_subscription_id'], name='subscriptio_stripe__aa726e_idx'), models.Index(fields=['stripe_customer_id'], name='subscriptio_stripe__84f275_idx'), models.Index(fields=['status', 'current_period_end'], name='subscriptio_status_302dc0_idx')],
            },
        ),
    ]
