# Generated by Django 5.0.1 on 2025-12-02 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0003_account_downgrade_selection'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='accountdowngradeselection',
            new_name='account_dow_subscri_5c9474_idx',
            old_name='account_dow_subscr_8f9a2b_idx',
        ),
        migrations.RenameIndex(
            model_name='accountdowngradeselection',
            new_name='account_dow_deactiv_1e3655_idx',
            old_name='account_dow_deactiv_7c8d3e_idx',
        ),
        migrations.RenameIndex(
            model_name='accountdowngradeselection',
            new_name='account_dow_user_id_08022b_idx',
            old_name='account_dow_user_id_9e4f5a_idx',
        ),
        migrations.AlterField(
            model_name='pendingsubscription',
            name='plan',
            field=models.CharField(choices=[('premium', 'Premium'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], help_text='Subscription plan', max_length=20),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='pending_plan',
            field=models.CharField(blank=True, choices=[('premium', 'Premium'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], help_text='Pending plan to apply at next renewal', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='subscription',
            name='plan',
            field=models.CharField(choices=[('premium', 'Premium'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], help_text='Subscription plan (premium or pro)', max_length=20),
        ),
    ]
