"""
Insight models for storing and managing user financial insights.
"""

import uuid
from django.db import models
from django.contrib.auth import get_user_model

User = get_user_model()


class InsightType(models.TextChoices):
    """Types of insights that can be generated."""

    SUBSCRIPTION = "subscription", "Subscription Pattern"
    UNUSUAL_SPENDING = "unusual_spending", "Unusual Spending"
    MERCHANT_PATTERN = "merchant_pattern", "Merchant Pattern"
    SAVINGS_OPPORTUNITY = "savings_opportunity", "Savings Opportunity"
    INCOME_ANALYSIS = "income_analysis", "Income Analysis"
    SPENDING_TREND = "spending_trend", "Spending Trend"
    BUDGET_INSIGHT = "budget_insight", "Budget Insight"
    AI_RECOMMENDATION = "ai_recommendation", "AI Recommendation"


class InsightPriority(models.TextChoices):
    """Priority levels for insights."""

    HIGH = "high", "High"
    MEDIUM = "medium", "Medium"
    LOW = "low", "Low"


class Insight(models.Model):
    """
    Stores generated financial insights for users.

    Insights are proactively generated by analyzing user's financial data
    and can be dismissed, read, or acted upon.
    """

    insight_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="insights")
    insight_type = models.CharField(
        max_length=50, choices=InsightType.choices, help_text="Type of insight"
    )
    title = models.CharField(max_length=200, help_text="Short title for the insight")
    description = models.TextField(help_text="Detailed description of the insight")
    priority = models.CharField(
        max_length=20,
        choices=InsightPriority.choices,
        default=InsightPriority.MEDIUM,
        help_text="Priority level of the insight",
    )
    is_dismissed = models.BooleanField(
        default=False, help_text="Whether the user has dismissed this insight"
    )
    is_read = models.BooleanField(
        default=False, help_text="Whether the user has read this insight"
    )
    metadata = models.JSONField(
        default=dict,
        blank=True,
        help_text="Additional data like related IDs, amounts, percentages",
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    expires_at = models.DateTimeField(
        null=True,
        blank=True,
        help_text="When this insight expires and should be hidden",
    )

    class Meta:
        ordering = ["-created_at"]
        verbose_name = "Insight"
        verbose_name_plural = "Insights"
        indexes = [
            models.Index(fields=["user", "is_dismissed"]),
            models.Index(fields=["user", "insight_type"]),
            models.Index(fields=["created_at"]),
        ]

    def __str__(self):
        return f"{self.insight_type}: {self.title}"

    def dismiss(self):
        """Mark insight as dismissed."""
        self.is_dismissed = True
        self.save(update_fields=["is_dismissed", "updated_at"])

    def mark_as_read(self):
        """Mark insight as read."""
        self.is_read = True
        self.save(update_fields=["is_read", "updated_at"])


class InsightFeedback(models.Model):
    """
    Stores user feedback on insights to improve future recommendations.
    """

    feedback_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    insight = models.ForeignKey(
        Insight, on_delete=models.CASCADE, related_name="feedback"
    )
    user = models.ForeignKey(
        User, on_delete=models.CASCADE, related_name="insight_feedback"
    )
    is_helpful = models.BooleanField(
        help_text="Whether the user found this insight helpful"
    )
    feedback_text = models.TextField(
        blank=True, help_text="Optional text feedback from user"
    )
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ["-created_at"]
        verbose_name = "Insight Feedback"
        verbose_name_plural = "Insight Feedback"
        unique_together = ["insight", "user"]

    def __str__(self):
        return f"Feedback on {self.insight.title} by {self.user.email}"
