# Generated by Django 5.0.1 on 2025-11-11 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_plaidwebhookevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='account',
            new_name='accounts_plaid_i_c17b55_idx',
            old_name='accounts_plaid_i_9b99f2_idx',
        ),
        migrations.RenameIndex(
            model_name='plaidwebhookevent',
            new_name='plaid_webho_item_id_6a80c4_idx',
            old_name='plaid_webh_item_id__3d0fd4_idx',
        ),
        migrations.AddField(
            model_name='account',
            name='custom_name',
            field=models.CharField(blank=True, help_text='User-defined custom name for the account', max_length=200, null=True),
        ),
    ]
