# Generated by Django 5.0.1 on 2025-11-14 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_add_custom_name_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='tour_done',
            field=models.BooleanField(default=False, help_text='Whether the user has completed the welcome tour'),
        ),
    ]
