# Generated by Django 5.0.1 on 2025-11-22 07:58

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_user_stripe_customer_id_user_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailChangeRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('new_email', models.EmailField(max_length=254)),
                ('token', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_change_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'email_change_requests',
                'indexes': [models.Index(fields=['token'], name='email_chang_token_667ba5_idx'), models.Index(fields=['user', 'created_at'], name='email_chang_user_id_388d6a_idx')],
            },
        ),
    ]
