# Generated by Django 5.0.1 on 2025-12-10 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_add_mfa_backup_codes'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='plaid_apr',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Annual Percentage Rate from Plaid', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='plaid_credit_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Credit limit for credit cards', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='plaid_interest_rate',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Interest rate for loans', max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='plaid_last_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Last payment amount', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='plaid_last_payment_date',
            field=models.DateField(blank=True, help_text='Date of last payment', null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='plaid_liabilities_last_updated',
            field=models.DateTimeField(blank=True, help_text='Last time liability data was fetched from Plaid', null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='plaid_loan_term',
            field=models.CharField(blank=True, help_text="Loan term (e.g., '30 year', '15 year')", max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='plaid_loan_type',
            field=models.CharField(blank=True, help_text='Type of loan (conventional, fha, student, auto, personal, etc.)', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='plaid_maturity_date',
            field=models.DateField(blank=True, help_text='Date loan matures/ends', null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='plaid_minimum_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum payment amount due', max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='plaid_next_payment_due_date',
            field=models.DateField(blank=True, help_text='Next payment due date', null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='plaid_origination_date',
            field=models.DateField(blank=True, help_text='Date loan was originated', null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='plaid_payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Regular payment amount for loans', max_digits=12, null=True),
        ),
    ]
