# Generated by Django 5.0.1 on 2025-12-16 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_add_plaid_liabilities_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
