# Generated by Django 5.0.1 on 2025-12-18 01:27


from django.db import models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_alter_user_email_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_number_masked",
            field=models.CharField(
                help_text="Last 4 digits for display", max_length=50
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="custom_name",
            field=models.CharField(
                blank=True,
                help_text="User-defined custom name for the account",
                max_length=200,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="account",
            name="institution_name",
            field=models.CharField(max_length=255),
        ),
    ]
