# Generated by Django 5.0.1 on 2025-12-18 01:30


from django.db import models
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0013_alter_account_account_number_masked_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="account_number_masked",
            field=models.CharField(
                help_text="Last 4 digits for display", max_length=255
            ),
        ),
    ]
