# Generated by Django 5.0.1 on 2025-12-06 07:21

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('transactions', '0003_receipt_transactionsplit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DebtAccount',
            fields=[
                ('debt_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Debt name (e.g., Chase Credit Card)', max_length=200)),
                ('debt_type', models.CharField(choices=[('credit_card', 'Credit Card'), ('personal_loan', 'Personal Loan'), ('mortgage', 'Mortgage'), ('auto_loan', 'Auto Loan'), ('student_loan', 'Student Loan'), ('other', 'Other')], default='other', max_length=20)),
                ('current_balance', models.DecimalField(decimal_places=2, help_text='Current outstanding balance', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('original_balance', models.DecimalField(decimal_places=2, help_text='Original loan/debt amount', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual Percentage Rate (APR)', max_digits=5, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('100.00'))])),
                ('minimum_payment', models.DecimalField(decimal_places=2, help_text='Minimum monthly payment', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('due_day', models.IntegerField(help_text='Day of month when payment is due', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(31)])),
                ('creditor_name', models.CharField(blank=True, help_text='Creditor/lender name', max_length=200)),
                ('account_number_masked', models.CharField(blank=True, help_text='Last 4 digits', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('paid_off', 'Paid Off'), ('closed', 'Closed')], default='active', max_length=20)),
                ('opened_date', models.DateField(blank=True, help_text='Date debt was opened', null=True)),
                ('target_payoff_date', models.DateField(blank=True, help_text='Target date to pay off', null=True)),
                ('last_payment_date', models.DateField(blank=True, help_text='Last payment date', null=True)),
                ('last_payment_amount', models.DecimalField(blank=True, decimal_places=2, help_text='Last payment amount', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Debt Account',
                'verbose_name_plural': 'Debt Accounts',
                'db_table': 'debts',
                'ordering': ['-current_balance', 'name'],
            },
        ),
        migrations.CreateModel(
            name='DebtPayment',
            fields=[
                ('payment_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Total payment amount', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('payment_type', models.CharField(choices=[('minimum', 'Minimum Payment'), ('extra', 'Extra Payment'), ('full', 'Full Payoff')], default='minimum', max_length=20)),
                ('applied_to_principal', models.DecimalField(decimal_places=2, help_text='Amount applied to principal', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('applied_to_interest', models.DecimalField(decimal_places=2, help_text='Amount applied to interest', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))])),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('debt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='debts.debtaccount')),
                ('transaction', models.ForeignKey(blank=True, help_text='Linked transaction', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='debt_payments', to='transactions.transaction')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_payments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Debt Payment',
                'verbose_name_plural': 'Debt Payments',
                'db_table': 'debt_payments',
                'ordering': ['-payment_date', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DebtPayoffStrategy',
            fields=[
                ('strategy_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('strategy_type', models.CharField(choices=[('snowball', 'Snowball (Smallest Balance First)'), ('avalanche', 'Avalanche (Highest Interest First)'), ('custom', 'Custom Order')], max_length=20)),
                ('monthly_budget', models.DecimalField(decimal_places=2, help_text='Total monthly budget for debt payments', max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('priority_order', models.JSONField(default=list, help_text='List of debt_ids in priority order (for custom strategy)')),
                ('target_payoff_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debt_strategies', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Debt Payoff Strategy',
                'verbose_name_plural': 'Debt Payoff Strategies',
                'db_table': 'debt_strategies',
                'ordering': ['-is_active', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='debtaccount',
            index=models.Index(fields=['user', 'is_active'], name='debts_user_id_a11fbe_idx'),
        ),
        migrations.AddIndex(
            model_name='debtaccount',
            index=models.Index(fields=['user', 'status'], name='debts_user_id_71c247_idx'),
        ),
        migrations.AddIndex(
            model_name='debtaccount',
            index=models.Index(fields=['debt_type'], name='debts_debt_ty_0e9388_idx'),
        ),
        migrations.AddIndex(
            model_name='debtaccount',
            index=models.Index(fields=['due_day'], name='debts_due_day_3b1797_idx'),
        ),
        migrations.AddIndex(
            model_name='debtpayment',
            index=models.Index(fields=['debt', '-payment_date'], name='debt_paymen_debt_id_3da665_idx'),
        ),
        migrations.AddIndex(
            model_name='debtpayment',
            index=models.Index(fields=['user', '-payment_date'], name='debt_paymen_user_id_0461c4_idx'),
        ),
        migrations.AddIndex(
            model_name='debtpayment',
            index=models.Index(fields=['transaction'], name='debt_paymen_transac_2fb3d2_idx'),
        ),
        migrations.AddIndex(
            model_name='debtpayoffstrategy',
            index=models.Index(fields=['user', 'is_active'], name='debt_strate_user_id_43e907_idx'),
        ),
        migrations.AddIndex(
            model_name='debtpayoffstrategy',
            index=models.Index(fields=['strategy_type'], name='debt_strate_strateg_db21d8_idx'),
        ),
    ]
