# Generated by Django 5.0.1 on 2025-12-10 21:05

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtaccount',
            name='minimum_payment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Minimum monthly payment', max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.00'))]),
        ),
    ]
