# Generated by Django 5.0.1 on 2025-12-18 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('debts', '0003_alter_debtaccount_account_number_masked_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='debtaccount',
            name='account_number_masked',
            field=models.CharField(blank=True, help_text='Last 4 digits', max_length=255),
        ),
        migrations.AlterField(
            model_name='debtaccount',
            name='creditor_name',
            field=models.CharField(blank=True, help_text='Creditor/lender name', max_length=255),
        ),
        migrations.AlterField(
            model_name='debtaccount',
            name='name',
            field=models.CharField(help_text='Debt name (e.g., Chase Credit Card)', max_length=255),
        ),
        migrations.AlterField(
            model_name='debtaccount',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='debtpayment',
            name='notes',
            field=models.TextField(blank=True),
        ),
    ]
