# Generated by Django 5.0.1 on 2025-12-02 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='APIAnalyticsHourly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.DateTimeField(db_index=True)),
                ('endpoint', models.CharField(db_index=True, max_length=255)),
                ('method', models.CharField(db_index=True, max_length=10)),
                ('request_count', models.IntegerField(default=0)),
                ('error_count', models.IntegerField(default=0)),
                ('total_response_time_ms', models.FloatField(default=0)),
                ('min_response_time_ms', models.FloatField(blank=True, null=True)),
                ('max_response_time_ms', models.FloatField(blank=True, null=True)),
                ('total_request_size_bytes', models.BigIntegerField(default=0)),
                ('total_response_size_bytes', models.BigIntegerField(default=0)),
                ('status_2xx', models.IntegerField(default=0)),
                ('status_3xx', models.IntegerField(default=0)),
                ('status_4xx', models.IntegerField(default=0)),
                ('status_5xx', models.IntegerField(default=0)),
                ('unique_users', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'API Analytics (Hourly)',
                'verbose_name_plural': 'API Analytics (Hourly)',
                'ordering': ['-hour'],
                'indexes': [models.Index(fields=['hour', 'endpoint', 'method'], name='api_apianal_hour_c773b5_idx'), models.Index(fields=['hour'], name='api_apianal_hour_71f960_idx')],
                'unique_together': {('hour', 'endpoint', 'method')},
            },
        ),
        migrations.CreateModel(
            name='APIRequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('endpoint', models.CharField(db_index=True, max_length=255)),
                ('method', models.CharField(db_index=True, max_length=10)),
                ('status_code', models.IntegerField(db_index=True)),
                ('response_time_ms', models.FloatField()),
                ('request_size_bytes', models.IntegerField(blank=True, null=True)),
                ('response_size_bytes', models.IntegerField(blank=True, null=True)),
                ('user_id', models.IntegerField(blank=True, db_index=True, null=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True, default='')),
            ],
            options={
                'verbose_name': 'API Request Log',
                'verbose_name_plural': 'API Request Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['timestamp', 'endpoint'], name='api_apirequ_timesta_786867_idx'), models.Index(fields=['timestamp', 'status_code'], name='api_apirequ_timesta_c0f4a9_idx'), models.Index(fields=['endpoint', 'method'], name='api_apirequ_endpoin_47b275_idx')],
            },
        ),
    ]
