# Generated by Django 5.0.1 on 2025-12-02 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_api_analytics_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='apianalyticshourly',
            options={'ordering': ['-hour']},
        ),
        migrations.AlterModelOptions(
            name='apirequestlog',
            options={'ordering': ['-timestamp']},
        ),
        migrations.RemoveIndex(
            model_name='apianalyticshourly',
            name='api_apianal_hour_c773b5_idx',
        ),
        migrations.RemoveIndex(
            model_name='apianalyticshourly',
            name='api_apianal_hour_71f960_idx',
        ),
        migrations.RemoveIndex(
            model_name='apirequestlog',
            name='api_apirequ_timesta_786867_idx',
        ),
        migrations.RemoveIndex(
            model_name='apirequestlog',
            name='api_apirequ_timesta_c0f4a9_idx',
        ),
        migrations.RenameIndex(
            model_name='apirequestlog',
            new_name='api_request_endpoin_188ddd_idx',
            old_name='api_apirequ_endpoin_47b275_idx',
        ),
        migrations.RemoveField(
            model_name='apianalyticshourly',
            name='total_request_size_bytes',
        ),
        migrations.RemoveField(
            model_name='apianalyticshourly',
            name='total_response_size_bytes',
        ),
        migrations.RemoveField(
            model_name='apianalyticshourly',
            name='unique_users',
        ),
        migrations.AddField(
            model_name='apianalyticshourly',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='apianalyticshourly',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='apianalyticshourly',
            name='max_response_time_ms',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='apianalyticshourly',
            name='method',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='apianalyticshourly',
            name='min_response_time_ms',
            field=models.FloatField(default=0),
        ),
        migrations.AddIndex(
            model_name='apianalyticshourly',
            index=models.Index(fields=['-hour', 'endpoint'], name='api_analyti_hour_e041c3_idx'),
        ),
        migrations.AddIndex(
            model_name='apianalyticshourly',
            index=models.Index(fields=['endpoint', 'method', '-hour'], name='api_analyti_endpoin_b5921f_idx'),
        ),
        migrations.AddIndex(
            model_name='apirequestlog',
            index=models.Index(fields=['-timestamp', 'endpoint'], name='api_request_timesta_b7dbf8_idx'),
        ),
        migrations.AddIndex(
            model_name='apirequestlog',
            index=models.Index(fields=['status_code', '-timestamp'], name='api_request_status__0465a7_idx'),
        ),
        migrations.AlterModelTable(
            name='apianalyticshourly',
            table='api_analytics_hourly',
        ),
        migrations.AlterModelTable(
            name='apirequestlog',
            table='api_request_logs',
        ),
    ]
